'<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, dolorem officia? Dolor, velit corporis qui neque ipsam dolorem pariatur aperiam dignissimos eius corrupti amet quas, fugit ut laboriosam aut facere suscipit a, iure iste quia? Quo, recusandae ea cupiditate cumque harum delectus alias necessitatibus et dolores id. Quas, nam repudiandae maiores quaerat obcaecati esse placeat nisi consequuntur quis voluptatibus molestias officiis fugiat, iusto laboriosam </p>
<p>tempora. Iure adipisci earum excepturi maiores expedita quis eaque alias sapiente et dolorum eligendi voluptatibus, voluptas qui accusantium maxime commodi aspernatur eius saepe vero libero! Voluptatem ducimus, molestias dolorum nobis cupiditate sequi maxime iure, dignissimos vitae repudiandae consequuntur eligendi explicabo accusantium doloremque aliquid rem aut porro asperiores temporibus dolore. Assumenda, perspiciatis excepturi. Architecto possimus assumenda numquam! Sequi, quasi? Laudantium, nemo, dolore ipsam delectus cumque, tenetur nobis quia natus mollitia nisi aperiam sunt possimus placeat quis amet! Eveniet nemo ipsum quam excepturi blanditiis libero in quis id.</p>'

Post::create([
'title' => 'post 1',
'slug' => 'post-1',
'excerpt' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, dolorem officia? Dolor, velit corporis qui neque ipsam dolorem pariatur aperiam',
'body' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, dolorem officia? Dolor, velit corporis qui neque ipsam dolorem pariatur aperiam dignissimos eius corrupti amet quas, fugit ut laboriosam aut facere suscipit a, iure iste quia? Quo, recusandae ea cupiditate cumque harum delectus alias necessitatibus et dolores id. Quas, nam repudiandae maiores quaerat obcaecati esse placeat nisi consequuntur quis voluptatibus molestias officiis fugiat, iusto laboriosam </p>
<p>tempora. Iure adipisci earum excepturi maiores expedita quis eaque alias sapiente et dolorum eligendi voluptatibus, voluptas qui accusantium maxime commodi aspernatur eius saepe vero libero! Voluptatem ducimus, molestias dolorum nobis cupiditate sequi maxime iure, dignissimos vitae repudiandae consequuntur eligendi explicabo accusantium doloremque aliquid rem aut porro asperiores temporibus dolore. Assumenda, perspiciatis excepturi. Architecto possimus assumenda numquam! Sequi, quasi? Laudantium, nemo, dolore ipsam delectus cumque, tenetur nobis quia natus mollitia nisi aperiam sunt possimus placeat quis amet! Eveniet nemo ipsum quam excepturi blanditiis libero in quis id.</p>'
]);